RD /S /Q .\JCodes.Framework.WebUI\obj
RD /S /Q .\JCodes.Framework.WinFormUI\obj
RD /S /Q .\JCodes.Framework.AddIn\obj
RD /S /Q .\JCodes.Framework.BizControls\obj
RD /S /Q .\JCodes.Framework.BLL\obj
RD /S /Q .\JCodes.Framework.Common\obj
RD /S /Q .\JCodes.Framework.CommonControl\obj
RD /S /Q .\JCodes.Framework.DALFactory\obj
RD /S /Q .\JCodes.Framework.Entity\obj
RD /S /Q .\JCodes.Framework.Enum\obj
RD /S /Q .\JCodes.Framework.IDAL\obj
RD /S /Q .\JCodes.Framework.Model\obj
RD /S /Q .\JCodes.Framework.SQLServerDAL\obj
RD /S /Q .\JCodes.Framework.TestWinForm\obj
RD /S /Q .\JCodes.Framework.WebControls\obj
RD /S /Q .\JCodes.Framework.WebUI\obj